### ISSUE TITLE
Eliminate volatile overloads for types in Kokkos reductions

### ISSUE THREAD

**Issue by fnrizzi** [NexGenAnalytics/kokkos#2]
- [ ] identify where reductions are implemented
- [ ] remove volatile overloads
- [ ] ensure all tests work

**Comment by PhilMiller** [comment]
The tests should ideally not just pass, but also exhibit no errors from ThreadSanitizer or a comparable dynamic data race analysis. This may be complicated by the fact that ThreadSanitizer doesn't directly support atomic fence operations, only actual atomic loads and stores (cf https://github.com/google/sanitizers/issues/1352 since this deficiency isn't actually documented otherwise!)

**Comment by fnrizzi** [comment]
@PhilMiller yes, the issue wording/targets were not meant to be final, I just wanted to put something up to get the organization running. We can reword and revise things as needed. 
Related to this, I think that we might want to be cautious about how we do things: we do not want to overstep what they already do but if we find that we can/want to go a bit more in depth, propose it first to them.
